// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnicaIgnacioCasado.Data;

#nullable disable

namespace PruebaTecnicaIgnacioCasado.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120001341_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inscripciones", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Director"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Profesor"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Alumno"
                        });
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "General",
                            Email = "admin@colegio.com",
                            Nombre = "Claudio",
                            NumeroDocumento = "12311678",
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Perez",
                            Email = "profe.juan@colegio.com",
                            Nombre = "Juan",
                            NumeroDocumento = "12345699",
                            RolId = 2
                        },
                        new
                        {
                            Id = 3,
                            Apellido = " Perez",
                            Email = "alumno.juan@colegio.com",
                            Nombre = "Juan Perez",
                            NumeroDocumento = "66345699",
                            RolId = 3
                        });
                });

            modelBuilder.Entity("Inscripciones", b =>
                {
                    b.HasOne("PruebaTecnicaIgnacioCasado.Models.Entities.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PruebaTecnicaIgnacioCasado.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Curso", b =>
                {
                    b.HasOne("PruebaTecnicaIgnacioCasado.Models.Entities.Usuario", "Profesor")
                        .WithMany("CursosDictados")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Usuario", b =>
                {
                    b.HasOne("PruebaTecnicaIgnacioCasado.Models.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PruebaTecnicaIgnacioCasado.Models.Entities.Usuario", b =>
                {
                    b.Navigation("CursosDictados");
                });
#pragma warning restore 612, 618
        }
    }
}
